#!/bin/sh

# add all the jars anywhere in the lib/ directory to our classpath
here=$(dirname $0)
CLASSES=$here/bin
CLASSES=$CLASSES:$(echo $here/lib/*.jar | tr ' ' :)
CLASSES=$CLASSES:$here/book-nlp.jar

java -XX:ParallelGCThreads=4 -Xmx6000m -ea -classpath $CLASSES $*
